version: "3"

services:

  postgresql:
    image: postgres:12.2
    environment:
      POSTGRES_USER: hanna
      POSTGRES_PASSWORD: asdf12
      POSTGRES_DB: touristagencysystem
    ports:
        - "3769:5432"

